"""Reporter utilities for Williecat."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List

from ..core import ModuleResult, ReconContext


def render_markdown(context: ReconContext, results: Iterable[ModuleResult]) -> str:
    lines: List[str] = []
    target = context.domain or context.base_url or context.ip_address or "(unknown)"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S %Z")

    lines.append(f"# Williecat Recon Report – {target}")
    lines.append(f"**Timestamp (UTC):** {timestamp}")
    lines.append("**Mode:** Passive reconnaissance with standard library paws.\n")

    for result in results:
        heading = result.module.upper()
        lines.append(f"## {heading}")
        if result.error:
            lines.append(f"*Outcome:* :x: {result.error}\n")
            continue
        if result.data is None:
            lines.append("*Outcome:* :cat: No data collected.\n")
            continue

        lines.append("*Outcome:* :paw_prints: Data retrieved quietly.")
        if result.warnings:
            lines.append("*Warnings:*")
            for warning in result.warnings:
                lines.append(f"  - {warning}")
        lines.append("```")
        lines.append(json.dumps(result.data, indent=2, sort_keys=True))
        lines.append("```\n")

    lines.append("---")
    lines.append("*Generated by Williecat – Reconnaissance with Instinct*")
    return "\n".join(lines)


def write_markdown(path: Path, content: str) -> None:
    if not content.endswith("\n"):
        content = f"{content}\n"
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, results: Iterable[ModuleResult]) -> None:
    payload = [result.as_dict() for result in results]
    json_output = json.dumps(payload, indent=2, sort_keys=True)
    if not json_output.endswith("\n"):
        json_output = f"{json_output}\n"
    path.write_text(json_output, encoding="utf-8")
