"""Reporter utilities for Williecat."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List

from . import ModuleResult, ReconContext


def render_markdown(context: ReconContext, results: Iterable[ModuleResult]) -> str:
    lines: List[str] = []
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S %Z")
    lines.append(f"# Williecat Recon Report – {context.domain or context.base_url or context.ip_address}")
    lines.append(f"**Timestamp:** {timestamp}")
    scan_mode = "Passive Recon"
    lines.append(f"**Scan Mode:** {scan_mode}\n")

    for result in results:
        heading = result.module.upper()
        lines.append(f"## {heading}")
        if result.error:
            lines.append(f"Error: {result.error}\n")
            continue
        if result.data is None:
            lines.append("No data collected.\n")
            continue
        lines.append("```")
        lines.append(json.dumps(result.data, indent=2, sort_keys=True))
        lines.append("```\n")
    lines.append("---")
    lines.append("*Generated by Williecat – Reconnaissance with Instinct*")
    return "\n".join(lines)


def write_markdown(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, results: Iterable[ModuleResult]) -> None:
    payload = [result.as_dict() for result in results]
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
